// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Augeu
//
//	Augeu api
//	Schemes:
//	  http
//	  https
//	Host: localhost
//	BasePath: /api/v1
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
