// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Augeu api",
    "title": "Augeu",
    "version": "0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/get/applicationEvent": {
      "post": {
        "summary": "查询应用日志事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CommonQuery"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ApplicationEvent"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/clients": {
      "get": {
        "summary": "查询客户端列表",
        "responses": {
          "200": {
            "description": "成功返回客户端列表",
            "schema": {
              "$ref": "#/definitions/GetClientsResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/loginEvent": {
      "post": {
        "summary": "查询登录事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/GetLoginEventRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "$ref": "#/definitions/GetLoginEventResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/powershellEvent": {
      "post": {
        "summary": "查询PowerShell事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CommonQuery"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/EventPowerShell"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/processEvent": {
      "post": {
        "summary": "查询创建进程事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CommonQuery"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/EventCreateProcess"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/rdpEvent": {
      "post": {
        "summary": "查询RDP事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/GetRdpEventRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetRdpEventRepose"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/securityEvent": {
      "post": {
        "summary": "查询安全日志事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CommonQuery"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SecurityEvent"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/serviceEvent": {
      "post": {
        "summary": "查询服务事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CommonQuery"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回服务事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ServiceInfo"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/systemEvent": {
      "post": {
        "summary": "查询系统日志事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CommonQuery"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SystemEvent"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/getClientId": {
      "post": {
        "security": [],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/GetClientIdRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "返回 Augeu Api 版本号",
            "schema": {
              "$ref": "#/definitions/GetClientIdResponse"
            }
          },
          "401": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "security": [],
        "parameters": [
          {
            "name": "credentials",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "登录成功，返回 JWT 令牌",
            "schema": {
              "$ref": "#/definitions/LoginResponse"
            }
          },
          "401": {
            "description": "用户名或密码错误",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/register": {
      "post": {
        "security": [],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RegisterRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "注册成功",
            "schema": {
              "$ref": "#/definitions/RegisterResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/updata/applicationEvent": {
      "post": {
        "summary": "上传应用日志事件",
        "parameters": [
          {
            "name": "events",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ApplicationEvent"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/updata/powershellEvent": {
      "post": {
        "summary": "上传PowerShell事件",
        "parameters": [
          {
            "name": "events",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/EventPowerShell"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/updata/processEvent": {
      "post": {
        "summary": "上传创建进程事件",
        "parameters": [
          {
            "name": "events",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/EventCreateProcess"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/updata/securityEvent": {
      "post": {
        "summary": "上传安全日志事件",
        "parameters": [
          {
            "name": "events",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SecurityEvent"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          }
        }
      }
    },
    "/updata/serviceEvent": {
      "post": {
        "summary": "上传服务事件",
        "parameters": [
          {
            "name": "events",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ServiceEventUpload"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/updata/systemEvent": {
      "post": {
        "summary": "上传系统日志事件",
        "parameters": [
          {
            "name": "events",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SystemEvent"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/upload/loginEvent": {
      "post": {
        "security": [],
        "parameters": [
          {
            "name": "eventLog",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UploadLoginEventRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "事件日志上传成功",
            "schema": {
              "$ref": "#/definitions/UploadLoginEventResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/upload/rdpEvent": {
      "post": {
        "summary": "上传RDP事件",
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/UploadRDPEventRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/upload/userInfo": {
      "post": {
        "summary": "上传用户信息",
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/UploadUserInfoRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/version": {
      "get": {
        "security": [],
        "responses": {
          "200": {
            "description": "返回 Augeu Api 版本号",
            "schema": {
              "$ref": "#/definitions/Version"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ActionFailure": {
      "type": "object",
      "required": [
        "success",
        "from",
        "reason"
      ],
      "properties": {
        "from": {
          "type": "string",
          "default": "unknown"
        },
        "reason": {
          "type": "string",
          "default": "unexpected stack overflow"
        },
        "success": {
          "type": "boolean",
          "default": false
        }
      }
    },
    "ApplicationEvent": {
      "type": "object",
      "properties": {
        "CreateTime": {
          "type": "string",
          "format": "date-time"
        },
        "Description": {
          "type": "string"
        },
        "EventID": {
          "type": "string"
        },
        "ID": {
          "type": "integer"
        },
        "LevelDisplayName": {
          "type": "string"
        },
        "UUID": {
          "type": "string"
        }
      }
    },
    "BadRequestError": {
      "type": "object",
      "required": [
        "message",
        "code"
      ],
      "properties": {
        "code": {
          "description": "400",
          "type": "integer"
        },
        "message": {
          "description": "输入参数错误",
          "type": "string"
        }
      }
    },
    "ClientInfo": {
      "type": "object",
      "required": [
        "uuid",
        "ip",
        "SystemInfo"
      ],
      "properties": {
        "SystemInfo": {
          "description": "系统信息",
          "$ref": "#/definitions/SystemInfo"
        },
        "ip": {
          "description": "IP 地址列表",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "uuid": {
          "description": "唯一标识符",
          "type": "string"
        }
      }
    },
    "CommonQuery": {
      "type": "object",
      "properties": {
        "Uuid": {
          "type": "string"
        },
        "clientId": {
          "type": "string"
        },
        "ip": {
          "type": "string"
        }
      }
    },
    "EventBase": {
      "type": "object",
      "required": [
        "EventID",
        "uuid",
        "EventTime"
      ],
      "properties": {
        "EventID": {
          "type": "integer",
          "format": "int64"
        },
        "EventTime": {
          "description": "事件时间，格式：2006-01-02 15:04:05（注意原数据日期时间连写问题）",
          "type": "string",
          "format": "date-time"
        },
        "uuid": {
          "type": "string"
        }
      }
    },
    "EventCreateProcess": {
      "type": "object",
      "properties": {
        "CommandLine": {
          "type": "string"
        },
        "Create_User": {
          "type": "string"
        },
        "Create_User_Domain": {
          "type": "string"
        },
        "Description": {
          "type": "string"
        },
        "EventID": {
          "type": "string"
        },
        "ID": {
          "type": "integer"
        },
        "NewProcessName": {
          "type": "string"
        },
        "ParentProcessName": {
          "type": "string"
        },
        "UUID": {
          "type": "string"
        }
      }
    },
    "EventPowerShell": {
      "type": "object",
      "properties": {
        "Command": {
          "type": "string"
        },
        "Description": {
          "type": "string"
        },
        "EventID": {
          "type": "string"
        },
        "ID": {
          "type": "integer"
        },
        "UUID": {
          "type": "string"
        }
      }
    },
    "GetClientIdRequest": {
      "type": "object",
      "required": [
        "secret",
        "client_info"
      ],
      "properties": {
        "client_info": {
          "$ref": "#/definitions/ClientInfo"
        },
        "secret": {
          "description": "密钥",
          "type": "string"
        }
      }
    },
    "GetClientIdResponse": {
      "type": "object",
      "required": [
        "success",
        "clientId"
      ],
      "properties": {
        "clientId": {
          "type": "string",
          "default": "unknown"
        },
        "jwt": {
          "type": "string"
        },
        "success": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "GetClientsResponse": {
      "type": "object",
      "properties": {
        "clients": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ClientInfo"
          }
        }
      }
    },
    "GetLoginEventRequest": {
      "type": "object",
      "required": [
        "pageAndSize"
      ],
      "properties": {
        "Uuid": {
          "type": "string"
        },
        "clientId": {
          "type": "string"
        },
        "ip": {
          "type": "string"
        },
        "pageAndSize": {
          "$ref": "#/definitions/PageAndSize"
        }
      }
    },
    "GetLoginEventResponse": {
      "type": "object",
      "required": [
        "data",
        "page",
        "success"
      ],
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/LoginEvent"
          }
        },
        "page": {
          "$ref": "#/definitions/PageMeta"
        },
        "success": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "GetRdpEventRepose": {
      "type": "object",
      "required": [
        "data",
        "page",
        "success"
      ],
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/RDPEventUnit"
          }
        },
        "page": {
          "$ref": "#/definitions/PageMeta"
        },
        "success": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "GetRdpEventRequest": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/RDPEventUnit"
      }
    },
    "LoginEvent": {
      "type": "object",
      "required": [
        "EventID",
        "EventTime",
        "MachineUUID",
        "LoginType",
        "Username",
        "SubjectDomain",
        "SourceIP",
        "SubjectUser",
        "ProcessName"
      ],
      "properties": {
        "EventID": {
          "description": "事件ID，4624表示成功登录",
          "type": "integer"
        },
        "EventTime": {
          "description": "事件时间，格式：2006-01-02 15:04:05（注意原数据日期时间连写问题）",
          "type": "string",
          "format": "date-time"
        },
        "LoginType": {
          "description": "登录类型（Unknown表示无法识别的类型）",
          "type": "string"
        },
        "MachineUUID": {
          "description": "设备唯一标识符（UUID格式）",
          "type": "string"
        },
        "ProcessName": {
          "description": "触发登录的进程名（-表示无）",
          "type": "string"
        },
        "SourceIP": {
          "description": "源IP地址（-表示无）",
          "type": "string"
        },
        "SubjectDomain": {
          "description": "登录用户所属域（-表示无）",
          "type": "string"
        },
        "SubjectUser": {
          "description": "登录会话用户（-表示无）",
          "type": "string"
        },
        "Username": {
          "description": "登录用户名（SYSTEM表示系统账户）",
          "type": "string"
        }
      }
    },
    "LoginRequest": {
      "type": "object",
      "required": [
        "secrete",
        "name",
        "password"
      ],
      "properties": {
        "name": {
          "description": "用户名",
          "type": "string"
        },
        "password": {
          "description": "密码",
          "type": "string"
        },
        "secrete": {
          "description": "server 提供的secrete",
          "type": "string"
        }
      }
    },
    "LoginResponse": {
      "type": "object",
      "required": [
        "success",
        "jwt"
      ],
      "properties": {
        "jwt": {
          "description": "JWT 令牌",
          "type": "string",
          "default": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
        },
        "success": {
          "description": "是否成功",
          "type": "boolean",
          "default": true
        }
      }
    },
    "PageAndSize": {
      "type": "object",
      "required": [
        "page",
        "size"
      ],
      "properties": {
        "page": {
          "description": "页码",
          "type": "integer",
          "default": 1,
          "example": 1
        },
        "size": {
          "description": "每页数量",
          "type": "integer",
          "default": 10
        }
      }
    },
    "PageMeta": {
      "type": "object",
      "properties": {
        "page": {
          "type": "integer",
          "default": 1
        },
        "size": {
          "type": "integer",
          "default": 10
        },
        "total": {
          "type": "integer",
          "default": 0
        }
      }
    },
    "Patch": {
      "type": "object",
      "required": [
        "Description",
        "HotFixID",
        "InstalledBy",
        "InstalledOn"
      ],
      "properties": {
        "Description": {
          "description": "补丁描述",
          "type": "string"
        },
        "HotFixID": {
          "description": "热修复 ID",
          "type": "string"
        },
        "InstalledBy": {
          "description": "安装者",
          "type": "string"
        },
        "InstalledOn": {
          "description": "安装时间",
          "type": "string"
        }
      }
    },
    "QueryEvent": {
      "type": "object",
      "properties": {
        "clientId": {
          "description": "Client ID",
          "type": "string"
        },
        "eventId": {
          "description": "Event ID",
          "type": "integer"
        },
        "event_type": {
          "type": "string",
          "enum": [
            "login",
            "rdp",
            "service",
            "user",
            "createProcessLog",
            "powershell",
            "lsass",
            "system",
            "application",
            "security"
          ]
        },
        "ip": {
          "description": "IP",
          "type": "string",
          "example": "127.0.0.1"
        },
        "uuid": {
          "description": "UUID",
          "type": "string",
          "example": "1234567890"
        }
      }
    },
    "RDPEventUnit": {
      "type": "object",
      "required": [
        "Base",
        "AccountName",
        "AccountDomain",
        "ClientName",
        "ClientAddress"
      ],
      "properties": {
        "AccountDomain": {
          "description": "登录用户域",
          "type": "string"
        },
        "AccountName": {
          "description": "登录用户名",
          "type": "string",
          "example": "admin"
        },
        "Base": {
          "description": "事件基本信息",
          "$ref": "#/definitions/EventBase"
        },
        "ClientAddress": {
          "description": "客户端地址",
          "type": "string"
        },
        "ClientName": {
          "description": "客户端名称",
          "type": "string"
        }
      }
    },
    "RegisterRequest": {
      "type": "object",
      "required": [
        "userName",
        "passWord",
        "secrete"
      ],
      "properties": {
        "passWord": {
          "description": "密码",
          "type": "string"
        },
        "secrete": {
          "description": "server 提供的token",
          "type": "string"
        },
        "userName": {
          "description": "用户名",
          "type": "string"
        }
      }
    },
    "RegisterResponse": {
      "type": "object",
      "required": [
        "success",
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "default": "注册成功"
        },
        "success": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "SecurityEvent": {
      "type": "object",
      "properties": {
        "Description": {
          "type": "string"
        },
        "EventID": {
          "type": "string"
        },
        "ID": {
          "type": "integer"
        },
        "LevelDisplayName": {
          "type": "string"
        },
        "UUID": {
          "type": "string"
        }
      }
    },
    "ServiceEventUpload": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "event_id": {
          "type": "string"
        }
      }
    },
    "ServiceInfo": {
      "type": "object",
      "properties": {
        "Account": {
          "type": "string"
        },
        "Description": {
          "type": "string"
        },
        "EventID": {
          "type": "string"
        },
        "ID": {
          "type": "integer"
        },
        "ImagePath": {
          "type": "string"
        },
        "ServiceName": {
          "type": "string"
        },
        "StartType": {
          "type": "string"
        },
        "UUID": {
          "type": "string"
        }
      }
    },
    "SuccessResponse": {
      "type": "object",
      "required": [
        "code",
        "message",
        "success"
      ],
      "properties": {
        "code": {
          "description": "状态码",
          "type": "integer",
          "default": 0
        },
        "message": {
          "description": "状态描述",
          "type": "string",
          "default": "success"
        },
        "success": {
          "description": "是否成功",
          "type": "boolean",
          "default": true
        }
      }
    },
    "SystemEvent": {
      "type": "object",
      "properties": {
        "Description": {
          "type": "string"
        },
        "EventID": {
          "type": "string"
        },
        "ID": {
          "type": "integer"
        },
        "LevelDisplayName": {
          "type": "string"
        },
        "UUID": {
          "type": "string"
        }
      }
    },
    "SystemInfo": {
      "type": "object",
      "required": [
        "os_name",
        "os_version",
        "os_arch",
        "patchs"
      ],
      "properties": {
        "os_arch": {
          "description": "操作系统架构",
          "type": "string"
        },
        "os_name": {
          "description": "操作系统名称",
          "type": "string"
        },
        "os_version": {
          "description": "操作系统版本",
          "type": "string"
        },
        "patchs": {
          "description": "补丁列表",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Patch"
          }
        }
      }
    },
    "UnauthorizedError": {
      "type": "object",
      "required": [
        "message",
        "code"
      ],
      "properties": {
        "code": {
          "description": "403",
          "type": "integer"
        },
        "message": {
          "description": "没有权限",
          "type": "string"
        }
      }
    },
    "UploadLoginEventRequest": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/LoginEvent"
      }
    },
    "UploadLoginEventResponse": {
      "type": "object",
      "required": [
        "success",
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "default": "事件日志上传成功"
        },
        "success": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "UploadRDPEventRequest": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/RDPEventUnit"
      }
    },
    "UploadUserInfoRequest": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/UserInfo"
      }
    },
    "UserInfo": {
      "type": "object",
      "required": [
        "name",
        "description",
        "localAccount",
        "sid",
        "isFocus",
        "uuid"
      ],
      "properties": {
        "description": {
          "description": "描述",
          "type": "string"
        },
        "isFocus": {
          "description": "是否是可疑的用户",
          "type": "boolean"
        },
        "localAccount": {
          "description": "是否本地账户",
          "type": "boolean"
        },
        "name": {
          "description": "名字",
          "type": "string"
        },
        "sid": {
          "description": "SID",
          "type": "string"
        },
        "uuid": {
          "description": "UUID",
          "type": "string"
        }
      }
    },
    "Version": {
      "type": "object",
      "properties": {
        "version": {
          "description": "版本号",
          "type": "string",
          "default": "0.0.1"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Augeu api",
    "title": "Augeu",
    "version": "0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/get/applicationEvent": {
      "post": {
        "summary": "查询应用日志事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CommonQuery"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ApplicationEvent"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/clients": {
      "get": {
        "summary": "查询客户端列表",
        "responses": {
          "200": {
            "description": "成功返回客户端列表",
            "schema": {
              "$ref": "#/definitions/GetClientsResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/loginEvent": {
      "post": {
        "summary": "查询登录事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/GetLoginEventRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "$ref": "#/definitions/GetLoginEventResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/powershellEvent": {
      "post": {
        "summary": "查询PowerShell事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CommonQuery"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/EventPowerShell"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/processEvent": {
      "post": {
        "summary": "查询创建进程事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CommonQuery"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/EventCreateProcess"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/rdpEvent": {
      "post": {
        "summary": "查询RDP事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/GetRdpEventRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetRdpEventRepose"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/securityEvent": {
      "post": {
        "summary": "查询安全日志事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CommonQuery"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SecurityEvent"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/serviceEvent": {
      "post": {
        "summary": "查询服务事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CommonQuery"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回服务事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ServiceInfo"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/get/systemEvent": {
      "post": {
        "summary": "查询系统日志事件",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/CommonQuery"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功返回事件数组",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SystemEvent"
              }
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/getClientId": {
      "post": {
        "security": [],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/GetClientIdRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "返回 Augeu Api 版本号",
            "schema": {
              "$ref": "#/definitions/GetClientIdResponse"
            }
          },
          "401": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "security": [],
        "parameters": [
          {
            "name": "credentials",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "登录成功，返回 JWT 令牌",
            "schema": {
              "$ref": "#/definitions/LoginResponse"
            }
          },
          "401": {
            "description": "用户名或密码错误",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/register": {
      "post": {
        "security": [],
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RegisterRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "注册成功",
            "schema": {
              "$ref": "#/definitions/RegisterResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/updata/applicationEvent": {
      "post": {
        "summary": "上传应用日志事件",
        "parameters": [
          {
            "name": "events",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ApplicationEvent"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/updata/powershellEvent": {
      "post": {
        "summary": "上传PowerShell事件",
        "parameters": [
          {
            "name": "events",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/EventPowerShell"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/updata/processEvent": {
      "post": {
        "summary": "上传创建进程事件",
        "parameters": [
          {
            "name": "events",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/EventCreateProcess"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/updata/securityEvent": {
      "post": {
        "summary": "上传安全日志事件",
        "parameters": [
          {
            "name": "events",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SecurityEvent"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          }
        }
      }
    },
    "/updata/serviceEvent": {
      "post": {
        "summary": "上传服务事件",
        "parameters": [
          {
            "name": "events",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ServiceEventUpload"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/updata/systemEvent": {
      "post": {
        "summary": "上传系统日志事件",
        "parameters": [
          {
            "name": "events",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SystemEvent"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/upload/loginEvent": {
      "post": {
        "security": [],
        "parameters": [
          {
            "name": "eventLog",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UploadLoginEventRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "事件日志上传成功",
            "schema": {
              "$ref": "#/definitions/UploadLoginEventResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/upload/rdpEvent": {
      "post": {
        "summary": "上传RDP事件",
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/UploadRDPEventRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/upload/userInfo": {
      "post": {
        "summary": "上传用户信息",
        "parameters": [
          {
            "name": "data",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/UploadUserInfoRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "上传成功",
            "schema": {
              "$ref": "#/definitions/SuccessResponse"
            }
          },
          "400": {
            "description": "输入参数错误",
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            }
          },
          "403": {
            "description": "没有权限",
            "schema": {
              "$ref": "#/definitions/UnauthorizedError"
            }
          },
          "500": {
            "description": "内部错误",
            "schema": {
              "$ref": "#/definitions/ActionFailure"
            }
          }
        }
      }
    },
    "/version": {
      "get": {
        "security": [],
        "responses": {
          "200": {
            "description": "返回 Augeu Api 版本号",
            "schema": {
              "$ref": "#/definitions/Version"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ActionFailure": {
      "type": "object",
      "required": [
        "success",
        "from",
        "reason"
      ],
      "properties": {
        "from": {
          "type": "string",
          "default": "unknown"
        },
        "reason": {
          "type": "string",
          "default": "unexpected stack overflow"
        },
        "success": {
          "type": "boolean",
          "default": false
        }
      }
    },
    "ApplicationEvent": {
      "type": "object",
      "properties": {
        "CreateTime": {
          "type": "string",
          "format": "date-time"
        },
        "Description": {
          "type": "string"
        },
        "EventID": {
          "type": "string"
        },
        "ID": {
          "type": "integer"
        },
        "LevelDisplayName": {
          "type": "string"
        },
        "UUID": {
          "type": "string"
        }
      }
    },
    "BadRequestError": {
      "type": "object",
      "required": [
        "message",
        "code"
      ],
      "properties": {
        "code": {
          "description": "400",
          "type": "integer"
        },
        "message": {
          "description": "输入参数错误",
          "type": "string"
        }
      }
    },
    "ClientInfo": {
      "type": "object",
      "required": [
        "uuid",
        "ip",
        "SystemInfo"
      ],
      "properties": {
        "SystemInfo": {
          "description": "系统信息",
          "$ref": "#/definitions/SystemInfo"
        },
        "ip": {
          "description": "IP 地址列表",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "uuid": {
          "description": "唯一标识符",
          "type": "string"
        }
      }
    },
    "CommonQuery": {
      "type": "object",
      "properties": {
        "Uuid": {
          "type": "string"
        },
        "clientId": {
          "type": "string"
        },
        "ip": {
          "type": "string"
        }
      }
    },
    "EventBase": {
      "type": "object",
      "required": [
        "EventID",
        "uuid",
        "EventTime"
      ],
      "properties": {
        "EventID": {
          "type": "integer",
          "format": "int64"
        },
        "EventTime": {
          "description": "事件时间，格式：2006-01-02 15:04:05（注意原数据日期时间连写问题）",
          "type": "string",
          "format": "date-time"
        },
        "uuid": {
          "type": "string"
        }
      }
    },
    "EventCreateProcess": {
      "type": "object",
      "properties": {
        "CommandLine": {
          "type": "string"
        },
        "Create_User": {
          "type": "string"
        },
        "Create_User_Domain": {
          "type": "string"
        },
        "Description": {
          "type": "string"
        },
        "EventID": {
          "type": "string"
        },
        "ID": {
          "type": "integer"
        },
        "NewProcessName": {
          "type": "string"
        },
        "ParentProcessName": {
          "type": "string"
        },
        "UUID": {
          "type": "string"
        }
      }
    },
    "EventPowerShell": {
      "type": "object",
      "properties": {
        "Command": {
          "type": "string"
        },
        "Description": {
          "type": "string"
        },
        "EventID": {
          "type": "string"
        },
        "ID": {
          "type": "integer"
        },
        "UUID": {
          "type": "string"
        }
      }
    },
    "GetClientIdRequest": {
      "type": "object",
      "required": [
        "secret",
        "client_info"
      ],
      "properties": {
        "client_info": {
          "$ref": "#/definitions/ClientInfo"
        },
        "secret": {
          "description": "密钥",
          "type": "string"
        }
      }
    },
    "GetClientIdResponse": {
      "type": "object",
      "required": [
        "success",
        "clientId"
      ],
      "properties": {
        "clientId": {
          "type": "string",
          "default": "unknown"
        },
        "jwt": {
          "type": "string"
        },
        "success": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "GetClientsResponse": {
      "type": "object",
      "properties": {
        "clients": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ClientInfo"
          }
        }
      }
    },
    "GetLoginEventRequest": {
      "type": "object",
      "required": [
        "pageAndSize"
      ],
      "properties": {
        "Uuid": {
          "type": "string"
        },
        "clientId": {
          "type": "string"
        },
        "ip": {
          "type": "string"
        },
        "pageAndSize": {
          "$ref": "#/definitions/PageAndSize"
        }
      }
    },
    "GetLoginEventResponse": {
      "type": "object",
      "required": [
        "data",
        "page",
        "success"
      ],
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/LoginEvent"
          }
        },
        "page": {
          "$ref": "#/definitions/PageMeta"
        },
        "success": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "GetRdpEventRepose": {
      "type": "object",
      "required": [
        "data",
        "page",
        "success"
      ],
      "properties": {
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/RDPEventUnit"
          }
        },
        "page": {
          "$ref": "#/definitions/PageMeta"
        },
        "success": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "GetRdpEventRequest": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/RDPEventUnit"
      }
    },
    "LoginEvent": {
      "type": "object",
      "required": [
        "EventID",
        "EventTime",
        "MachineUUID",
        "LoginType",
        "Username",
        "SubjectDomain",
        "SourceIP",
        "SubjectUser",
        "ProcessName"
      ],
      "properties": {
        "EventID": {
          "description": "事件ID，4624表示成功登录",
          "type": "integer"
        },
        "EventTime": {
          "description": "事件时间，格式：2006-01-02 15:04:05（注意原数据日期时间连写问题）",
          "type": "string",
          "format": "date-time"
        },
        "LoginType": {
          "description": "登录类型（Unknown表示无法识别的类型）",
          "type": "string"
        },
        "MachineUUID": {
          "description": "设备唯一标识符（UUID格式）",
          "type": "string"
        },
        "ProcessName": {
          "description": "触发登录的进程名（-表示无）",
          "type": "string"
        },
        "SourceIP": {
          "description": "源IP地址（-表示无）",
          "type": "string"
        },
        "SubjectDomain": {
          "description": "登录用户所属域（-表示无）",
          "type": "string"
        },
        "SubjectUser": {
          "description": "登录会话用户（-表示无）",
          "type": "string"
        },
        "Username": {
          "description": "登录用户名（SYSTEM表示系统账户）",
          "type": "string"
        }
      }
    },
    "LoginRequest": {
      "type": "object",
      "required": [
        "secrete",
        "name",
        "password"
      ],
      "properties": {
        "name": {
          "description": "用户名",
          "type": "string"
        },
        "password": {
          "description": "密码",
          "type": "string"
        },
        "secrete": {
          "description": "server 提供的secrete",
          "type": "string"
        }
      }
    },
    "LoginResponse": {
      "type": "object",
      "required": [
        "success",
        "jwt"
      ],
      "properties": {
        "jwt": {
          "description": "JWT 令牌",
          "type": "string",
          "default": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
        },
        "success": {
          "description": "是否成功",
          "type": "boolean",
          "default": true
        }
      }
    },
    "PageAndSize": {
      "type": "object",
      "required": [
        "page",
        "size"
      ],
      "properties": {
        "page": {
          "description": "页码",
          "type": "integer",
          "default": 1,
          "example": 1
        },
        "size": {
          "description": "每页数量",
          "type": "integer",
          "default": 10
        }
      }
    },
    "PageMeta": {
      "type": "object",
      "properties": {
        "page": {
          "type": "integer",
          "default": 1
        },
        "size": {
          "type": "integer",
          "default": 10
        },
        "total": {
          "type": "integer",
          "default": 0
        }
      }
    },
    "Patch": {
      "type": "object",
      "required": [
        "Description",
        "HotFixID",
        "InstalledBy",
        "InstalledOn"
      ],
      "properties": {
        "Description": {
          "description": "补丁描述",
          "type": "string"
        },
        "HotFixID": {
          "description": "热修复 ID",
          "type": "string"
        },
        "InstalledBy": {
          "description": "安装者",
          "type": "string"
        },
        "InstalledOn": {
          "description": "安装时间",
          "type": "string"
        }
      }
    },
    "QueryEvent": {
      "type": "object",
      "properties": {
        "clientId": {
          "description": "Client ID",
          "type": "string"
        },
        "eventId": {
          "description": "Event ID",
          "type": "integer"
        },
        "event_type": {
          "type": "string",
          "enum": [
            "login",
            "rdp",
            "service",
            "user",
            "createProcessLog",
            "powershell",
            "lsass",
            "system",
            "application",
            "security"
          ]
        },
        "ip": {
          "description": "IP",
          "type": "string",
          "example": "127.0.0.1"
        },
        "uuid": {
          "description": "UUID",
          "type": "string",
          "example": "1234567890"
        }
      }
    },
    "RDPEventUnit": {
      "type": "object",
      "required": [
        "Base",
        "AccountName",
        "AccountDomain",
        "ClientName",
        "ClientAddress"
      ],
      "properties": {
        "AccountDomain": {
          "description": "登录用户域",
          "type": "string"
        },
        "AccountName": {
          "description": "登录用户名",
          "type": "string",
          "example": "admin"
        },
        "Base": {
          "description": "事件基本信息",
          "$ref": "#/definitions/EventBase"
        },
        "ClientAddress": {
          "description": "客户端地址",
          "type": "string"
        },
        "ClientName": {
          "description": "客户端名称",
          "type": "string"
        }
      }
    },
    "RegisterRequest": {
      "type": "object",
      "required": [
        "userName",
        "passWord",
        "secrete"
      ],
      "properties": {
        "passWord": {
          "description": "密码",
          "type": "string"
        },
        "secrete": {
          "description": "server 提供的token",
          "type": "string"
        },
        "userName": {
          "description": "用户名",
          "type": "string"
        }
      }
    },
    "RegisterResponse": {
      "type": "object",
      "required": [
        "success",
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "default": "注册成功"
        },
        "success": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "SecurityEvent": {
      "type": "object",
      "properties": {
        "Description": {
          "type": "string"
        },
        "EventID": {
          "type": "string"
        },
        "ID": {
          "type": "integer"
        },
        "LevelDisplayName": {
          "type": "string"
        },
        "UUID": {
          "type": "string"
        }
      }
    },
    "ServiceEventUpload": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "event_id": {
          "type": "string"
        }
      }
    },
    "ServiceInfo": {
      "type": "object",
      "properties": {
        "Account": {
          "type": "string"
        },
        "Description": {
          "type": "string"
        },
        "EventID": {
          "type": "string"
        },
        "ID": {
          "type": "integer"
        },
        "ImagePath": {
          "type": "string"
        },
        "ServiceName": {
          "type": "string"
        },
        "StartType": {
          "type": "string"
        },
        "UUID": {
          "type": "string"
        }
      }
    },
    "SuccessResponse": {
      "type": "object",
      "required": [
        "code",
        "message",
        "success"
      ],
      "properties": {
        "code": {
          "description": "状态码",
          "type": "integer",
          "default": 0
        },
        "message": {
          "description": "状态描述",
          "type": "string",
          "default": "success"
        },
        "success": {
          "description": "是否成功",
          "type": "boolean",
          "default": true
        }
      }
    },
    "SystemEvent": {
      "type": "object",
      "properties": {
        "Description": {
          "type": "string"
        },
        "EventID": {
          "type": "string"
        },
        "ID": {
          "type": "integer"
        },
        "LevelDisplayName": {
          "type": "string"
        },
        "UUID": {
          "type": "string"
        }
      }
    },
    "SystemInfo": {
      "type": "object",
      "required": [
        "os_name",
        "os_version",
        "os_arch",
        "patchs"
      ],
      "properties": {
        "os_arch": {
          "description": "操作系统架构",
          "type": "string"
        },
        "os_name": {
          "description": "操作系统名称",
          "type": "string"
        },
        "os_version": {
          "description": "操作系统版本",
          "type": "string"
        },
        "patchs": {
          "description": "补丁列表",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Patch"
          }
        }
      }
    },
    "UnauthorizedError": {
      "type": "object",
      "required": [
        "message",
        "code"
      ],
      "properties": {
        "code": {
          "description": "403",
          "type": "integer"
        },
        "message": {
          "description": "没有权限",
          "type": "string"
        }
      }
    },
    "UploadLoginEventRequest": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/LoginEvent"
      }
    },
    "UploadLoginEventResponse": {
      "type": "object",
      "required": [
        "success",
        "message"
      ],
      "properties": {
        "message": {
          "type": "string",
          "default": "事件日志上传成功"
        },
        "success": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "UploadRDPEventRequest": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/RDPEventUnit"
      }
    },
    "UploadUserInfoRequest": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/UserInfo"
      }
    },
    "UserInfo": {
      "type": "object",
      "required": [
        "name",
        "description",
        "localAccount",
        "sid",
        "isFocus",
        "uuid"
      ],
      "properties": {
        "description": {
          "description": "描述",
          "type": "string"
        },
        "isFocus": {
          "description": "是否是可疑的用户",
          "type": "boolean"
        },
        "localAccount": {
          "description": "是否本地账户",
          "type": "boolean"
        },
        "name": {
          "description": "名字",
          "type": "string"
        },
        "sid": {
          "description": "SID",
          "type": "string"
        },
        "uuid": {
          "description": "UUID",
          "type": "string"
        }
      }
    },
    "Version": {
      "type": "object",
      "properties": {
        "version": {
          "description": "版本号",
          "type": "string",
          "default": "0.0.1"
        }
      }
    }
  }
}`))
}
