// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGetClientsHandlerFunc turns a function with the right signature into a get get clients handler
type GetGetClientsHandlerFunc func(GetGetClientsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGetClientsHandlerFunc) Handle(params GetGetClientsParams) middleware.Responder {
	return fn(params)
}

// GetGetClientsHandler interface for that can handle valid get get clients params
type GetGetClientsHandler interface {
	Handle(GetGetClientsParams) middleware.Responder
}

// NewGetGetClients creates a new http.Handler for the get get clients operation
func NewGetGetClients(ctx *middleware.Context, handler GetGetClientsHandler) *GetGetClients {
	return &GetGetClients{Context: ctx, Handler: handler}
}

/*
	GetGetClients swagger:route GET /get/clients getGetClients

查询客户端列表
*/
type GetGetClients struct {
	Context *middleware.Context
	Handler GetGetClientsHandler
}

func (o *GetGetClients) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGetClientsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
