// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// GetGetClientsOKCode is the HTTP code returned for type GetGetClientsOK
const GetGetClientsOKCode int = 200

/*
GetGetClientsOK 成功返回客户端列表

swagger:response getGetClientsOK
*/
type GetGetClientsOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetClientsResponse `json:"body,omitempty"`
}

// NewGetGetClientsOK creates GetGetClientsOK with default headers values
func NewGetGetClientsOK() *GetGetClientsOK {

	return &GetGetClientsOK{}
}

// WithPayload adds the payload to the get get clients o k response
func (o *GetGetClientsOK) WithPayload(payload *models.GetClientsResponse) *GetGetClientsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get clients o k response
func (o *GetGetClientsOK) SetPayload(payload *models.GetClientsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetClientsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGetClientsBadRequestCode is the HTTP code returned for type GetGetClientsBadRequest
const GetGetClientsBadRequestCode int = 400

/*
GetGetClientsBadRequest 输入参数错误

swagger:response getGetClientsBadRequest
*/
type GetGetClientsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewGetGetClientsBadRequest creates GetGetClientsBadRequest with default headers values
func NewGetGetClientsBadRequest() *GetGetClientsBadRequest {

	return &GetGetClientsBadRequest{}
}

// WithPayload adds the payload to the get get clients bad request response
func (o *GetGetClientsBadRequest) WithPayload(payload *models.BadRequestError) *GetGetClientsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get clients bad request response
func (o *GetGetClientsBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetClientsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGetClientsForbiddenCode is the HTTP code returned for type GetGetClientsForbidden
const GetGetClientsForbiddenCode int = 403

/*
GetGetClientsForbidden 没有权限

swagger:response getGetClientsForbidden
*/
type GetGetClientsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.UnauthorizedError `json:"body,omitempty"`
}

// NewGetGetClientsForbidden creates GetGetClientsForbidden with default headers values
func NewGetGetClientsForbidden() *GetGetClientsForbidden {

	return &GetGetClientsForbidden{}
}

// WithPayload adds the payload to the get get clients forbidden response
func (o *GetGetClientsForbidden) WithPayload(payload *models.UnauthorizedError) *GetGetClientsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get clients forbidden response
func (o *GetGetClientsForbidden) SetPayload(payload *models.UnauthorizedError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetClientsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGetClientsInternalServerErrorCode is the HTTP code returned for type GetGetClientsInternalServerError
const GetGetClientsInternalServerErrorCode int = 500

/*
GetGetClientsInternalServerError 内部错误

swagger:response getGetClientsInternalServerError
*/
type GetGetClientsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ActionFailure `json:"body,omitempty"`
}

// NewGetGetClientsInternalServerError creates GetGetClientsInternalServerError with default headers values
func NewGetGetClientsInternalServerError() *GetGetClientsInternalServerError {

	return &GetGetClientsInternalServerError{}
}

// WithPayload adds the payload to the get get clients internal server error response
func (o *GetGetClientsInternalServerError) WithPayload(payload *models.ActionFailure) *GetGetClientsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get clients internal server error response
func (o *GetGetClientsInternalServerError) SetPayload(payload *models.ActionFailure) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetClientsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
