// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// PostUpdataSecurityEventOKCode is the HTTP code returned for type PostUpdataSecurityEventOK
const PostUpdataSecurityEventOKCode int = 200

/*
PostUpdataSecurityEventOK 上传成功

swagger:response postUpdataSecurityEventOK
*/
type PostUpdataSecurityEventOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewPostUpdataSecurityEventOK creates PostUpdataSecurityEventOK with default headers values
func NewPostUpdataSecurityEventOK() *PostUpdataSecurityEventOK {

	return &PostUpdataSecurityEventOK{}
}

// WithPayload adds the payload to the post updata security event o k response
func (o *PostUpdataSecurityEventOK) WithPayload(payload *models.SuccessResponse) *PostUpdataSecurityEventOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post updata security event o k response
func (o *PostUpdataSecurityEventOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUpdataSecurityEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
