// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUpdataProcessEventHandlerFunc turns a function with the right signature into a post updata process event handler
type PostUpdataProcessEventHandlerFunc func(PostUpdataProcessEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUpdataProcessEventHandlerFunc) Handle(params PostUpdataProcessEventParams) middleware.Responder {
	return fn(params)
}

// PostUpdataProcessEventHandler interface for that can handle valid post updata process event params
type PostUpdataProcessEventHandler interface {
	Handle(PostUpdataProcessEventParams) middleware.Responder
}

// NewPostUpdataProcessEvent creates a new http.Handler for the post updata process event operation
func NewPostUpdataProcessEvent(ctx *middleware.Context, handler PostUpdataProcessEventHandler) *PostUpdataProcessEvent {
	return &PostUpdataProcessEvent{Context: ctx, Handler: handler}
}

/*
	PostUpdataProcessEvent swagger:route POST /updata/processEvent postUpdataProcessEvent

上传创建进程事件
*/
type PostUpdataProcessEvent struct {
	Context *middleware.Context
	Handler PostUpdataProcessEventHandler
}

func (o *PostUpdataProcessEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUpdataProcessEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
