// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUpdataPowershellEventHandlerFunc turns a function with the right signature into a post updata powershell event handler
type PostUpdataPowershellEventHandlerFunc func(PostUpdataPowershellEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUpdataPowershellEventHandlerFunc) Handle(params PostUpdataPowershellEventParams) middleware.Responder {
	return fn(params)
}

// PostUpdataPowershellEventHandler interface for that can handle valid post updata powershell event params
type PostUpdataPowershellEventHandler interface {
	Handle(PostUpdataPowershellEventParams) middleware.Responder
}

// NewPostUpdataPowershellEvent creates a new http.Handler for the post updata powershell event operation
func NewPostUpdataPowershellEvent(ctx *middleware.Context, handler PostUpdataPowershellEventHandler) *PostUpdataPowershellEvent {
	return &PostUpdataPowershellEvent{Context: ctx, Handler: handler}
}

/*
	PostUpdataPowershellEvent swagger:route POST /updata/powershellEvent postUpdataPowershellEvent

上传PowerShell事件
*/
type PostUpdataPowershellEvent struct {
	Context *middleware.Context
	Handler PostUpdataPowershellEventHandler
}

func (o *PostUpdataPowershellEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUpdataPowershellEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
