// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"augeu/public/pkg/swaggerCore/models"
)

// NewPostUploadLoginEventParams creates a new PostUploadLoginEventParams object
//
// There are no default values defined in the spec.
func NewPostUploadLoginEventParams() PostUploadLoginEventParams {

	return PostUploadLoginEventParams{}
}

// PostUploadLoginEventParams contains all the bound params for the post upload login event operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostUploadLoginEvent
type PostUploadLoginEventParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	EventLog models.UploadLoginEventRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostUploadLoginEventParams() beforehand.
func (o *PostUploadLoginEventParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.UploadLoginEventRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("eventLog", "body", ""))
			} else {
				res = append(res, errors.NewParseError("eventLog", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.EventLog = body
			}
		}
	} else {
		res = append(res, errors.Required("eventLog", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
