// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// PostUpdataPowershellEventOKCode is the HTTP code returned for type PostUpdataPowershellEventOK
const PostUpdataPowershellEventOKCode int = 200

/*
PostUpdataPowershellEventOK 上传成功

swagger:response postUpdataPowershellEventOK
*/
type PostUpdataPowershellEventOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuccessResponse `json:"body,omitempty"`
}

// NewPostUpdataPowershellEventOK creates PostUpdataPowershellEventOK with default headers values
func NewPostUpdataPowershellEventOK() *PostUpdataPowershellEventOK {

	return &PostUpdataPowershellEventOK{}
}

// WithPayload adds the payload to the post updata powershell event o k response
func (o *PostUpdataPowershellEventOK) WithPayload(payload *models.SuccessResponse) *PostUpdataPowershellEventOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post updata powershell event o k response
func (o *PostUpdataPowershellEventOK) SetPayload(payload *models.SuccessResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUpdataPowershellEventOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUpdataPowershellEventBadRequestCode is the HTTP code returned for type PostUpdataPowershellEventBadRequest
const PostUpdataPowershellEventBadRequestCode int = 400

/*
PostUpdataPowershellEventBadRequest 输入参数错误

swagger:response postUpdataPowershellEventBadRequest
*/
type PostUpdataPowershellEventBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewPostUpdataPowershellEventBadRequest creates PostUpdataPowershellEventBadRequest with default headers values
func NewPostUpdataPowershellEventBadRequest() *PostUpdataPowershellEventBadRequest {

	return &PostUpdataPowershellEventBadRequest{}
}

// WithPayload adds the payload to the post updata powershell event bad request response
func (o *PostUpdataPowershellEventBadRequest) WithPayload(payload *models.BadRequestError) *PostUpdataPowershellEventBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post updata powershell event bad request response
func (o *PostUpdataPowershellEventBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUpdataPowershellEventBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUpdataPowershellEventForbiddenCode is the HTTP code returned for type PostUpdataPowershellEventForbidden
const PostUpdataPowershellEventForbiddenCode int = 403

/*
PostUpdataPowershellEventForbidden 没有权限

swagger:response postUpdataPowershellEventForbidden
*/
type PostUpdataPowershellEventForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.UnauthorizedError `json:"body,omitempty"`
}

// NewPostUpdataPowershellEventForbidden creates PostUpdataPowershellEventForbidden with default headers values
func NewPostUpdataPowershellEventForbidden() *PostUpdataPowershellEventForbidden {

	return &PostUpdataPowershellEventForbidden{}
}

// WithPayload adds the payload to the post updata powershell event forbidden response
func (o *PostUpdataPowershellEventForbidden) WithPayload(payload *models.UnauthorizedError) *PostUpdataPowershellEventForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post updata powershell event forbidden response
func (o *PostUpdataPowershellEventForbidden) SetPayload(payload *models.UnauthorizedError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUpdataPowershellEventForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUpdataPowershellEventInternalServerErrorCode is the HTTP code returned for type PostUpdataPowershellEventInternalServerError
const PostUpdataPowershellEventInternalServerErrorCode int = 500

/*
PostUpdataPowershellEventInternalServerError 内部错误

swagger:response postUpdataPowershellEventInternalServerError
*/
type PostUpdataPowershellEventInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ActionFailure `json:"body,omitempty"`
}

// NewPostUpdataPowershellEventInternalServerError creates PostUpdataPowershellEventInternalServerError with default headers values
func NewPostUpdataPowershellEventInternalServerError() *PostUpdataPowershellEventInternalServerError {

	return &PostUpdataPowershellEventInternalServerError{}
}

// WithPayload adds the payload to the post updata powershell event internal server error response
func (o *PostUpdataPowershellEventInternalServerError) WithPayload(payload *models.ActionFailure) *PostUpdataPowershellEventInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post updata powershell event internal server error response
func (o *PostUpdataPowershellEventInternalServerError) SetPayload(payload *models.ActionFailure) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUpdataPowershellEventInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
