// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUploadLoginEventHandlerFunc turns a function with the right signature into a post upload login event handler
type PostUploadLoginEventHandlerFunc func(PostUploadLoginEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUploadLoginEventHandlerFunc) Handle(params PostUploadLoginEventParams) middleware.Responder {
	return fn(params)
}

// PostUploadLoginEventHandler interface for that can handle valid post upload login event params
type PostUploadLoginEventHandler interface {
	Handle(PostUploadLoginEventParams) middleware.Responder
}

// NewPostUploadLoginEvent creates a new http.Handler for the post upload login event operation
func NewPostUploadLoginEvent(ctx *middleware.Context, handler PostUploadLoginEventHandler) *PostUploadLoginEvent {
	return &PostUploadLoginEvent{Context: ctx, Handler: handler}
}

/*
	PostUploadLoginEvent swagger:route POST /upload/loginEvent postUploadLoginEvent

PostUploadLoginEvent post upload login event API
*/
type PostUploadLoginEvent struct {
	Context *middleware.Context
	Handler PostUploadLoginEventHandler
}

func (o *PostUploadLoginEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUploadLoginEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
