// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUpdataRdpEventHandlerFunc turns a function with the right signature into a post updata rdp event handler
type PostUpdataRdpEventHandlerFunc func(PostUpdataRdpEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUpdataRdpEventHandlerFunc) Handle(params PostUpdataRdpEventParams) middleware.Responder {
	return fn(params)
}

// PostUpdataRdpEventHandler interface for that can handle valid post updata rdp event params
type PostUpdataRdpEventHandler interface {
	Handle(PostUpdataRdpEventParams) middleware.Responder
}

// NewPostUpdataRdpEvent creates a new http.Handler for the post updata rdp event operation
func NewPostUpdataRdpEvent(ctx *middleware.Context, handler PostUpdataRdpEventHandler) *PostUpdataRdpEvent {
	return &PostUpdataRdpEvent{Context: ctx, Handler: handler}
}

/*
	PostUpdataRdpEvent swagger:route POST /updata/rdpEvent postUpdataRdpEvent

上传RDP事件
*/
type PostUpdataRdpEvent struct {
	Context *middleware.Context
	Handler PostUpdataRdpEventHandler
}

func (o *PostUpdataRdpEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUpdataRdpEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
