// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostGetPowershellEventHandlerFunc turns a function with the right signature into a post get powershell event handler
type PostGetPowershellEventHandlerFunc func(PostGetPowershellEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostGetPowershellEventHandlerFunc) Handle(params PostGetPowershellEventParams) middleware.Responder {
	return fn(params)
}

// PostGetPowershellEventHandler interface for that can handle valid post get powershell event params
type PostGetPowershellEventHandler interface {
	Handle(PostGetPowershellEventParams) middleware.Responder
}

// NewPostGetPowershellEvent creates a new http.Handler for the post get powershell event operation
func NewPostGetPowershellEvent(ctx *middleware.Context, handler PostGetPowershellEventHandler) *PostGetPowershellEvent {
	return &PostGetPowershellEvent{Context: ctx, Handler: handler}
}

/*
	PostGetPowershellEvent swagger:route POST /get/powershellEvent postGetPowershellEvent

查询PowerShell事件
*/
type PostGetPowershellEvent struct {
	Context *middleware.Context
	Handler PostGetPowershellEventHandler
}

func (o *PostGetPowershellEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostGetPowershellEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
