// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUpdataSecurityEventHandlerFunc turns a function with the right signature into a post updata security event handler
type PostUpdataSecurityEventHandlerFunc func(PostUpdataSecurityEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUpdataSecurityEventHandlerFunc) Handle(params PostUpdataSecurityEventParams) middleware.Responder {
	return fn(params)
}

// PostUpdataSecurityEventHandler interface for that can handle valid post updata security event params
type PostUpdataSecurityEventHandler interface {
	Handle(PostUpdataSecurityEventParams) middleware.Responder
}

// NewPostUpdataSecurityEvent creates a new http.Handler for the post updata security event operation
func NewPostUpdataSecurityEvent(ctx *middleware.Context, handler PostUpdataSecurityEventHandler) *PostUpdataSecurityEvent {
	return &PostUpdataSecurityEvent{Context: ctx, Handler: handler}
}

/*
	PostUpdataSecurityEvent swagger:route POST /updata/securityEvent postUpdataSecurityEvent

上传安全日志事件
*/
type PostUpdataSecurityEvent struct {
	Context *middleware.Context
	Handler PostUpdataSecurityEventHandler
}

func (o *PostUpdataSecurityEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUpdataSecurityEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
