// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUploadRdpEventHandlerFunc turns a function with the right signature into a post upload rdp event handler
type PostUploadRdpEventHandlerFunc func(PostUploadRdpEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUploadRdpEventHandlerFunc) Handle(params PostUploadRdpEventParams) middleware.Responder {
	return fn(params)
}

// PostUploadRdpEventHandler interface for that can handle valid post upload rdp event params
type PostUploadRdpEventHandler interface {
	Handle(PostUploadRdpEventParams) middleware.Responder
}

// NewPostUploadRdpEvent creates a new http.Handler for the post upload rdp event operation
func NewPostUploadRdpEvent(ctx *middleware.Context, handler PostUploadRdpEventHandler) *PostUploadRdpEvent {
	return &PostUploadRdpEvent{Context: ctx, Handler: handler}
}

/*
	PostUploadRdpEvent swagger:route POST /upload/rdpEvent postUploadRdpEvent

上传RDP事件
*/
type PostUploadRdpEvent struct {
	Context *middleware.Context
	Handler PostUploadRdpEventHandler
}

func (o *PostUploadRdpEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUploadRdpEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
