// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostGetProcessEventHandlerFunc turns a function with the right signature into a post get process event handler
type PostGetProcessEventHandlerFunc func(PostGetProcessEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostGetProcessEventHandlerFunc) Handle(params PostGetProcessEventParams) middleware.Responder {
	return fn(params)
}

// PostGetProcessEventHandler interface for that can handle valid post get process event params
type PostGetProcessEventHandler interface {
	Handle(PostGetProcessEventParams) middleware.Responder
}

// NewPostGetProcessEvent creates a new http.Handler for the post get process event operation
func NewPostGetProcessEvent(ctx *middleware.Context, handler PostGetProcessEventHandler) *PostGetProcessEvent {
	return &PostGetProcessEvent{Context: ctx, Handler: handler}
}

/*
	PostGetProcessEvent swagger:route POST /get/processEvent postGetProcessEvent

查询创建进程事件
*/
type PostGetProcessEvent struct {
	Context *middleware.Context
	Handler PostGetProcessEventHandler
}

func (o *PostGetProcessEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostGetProcessEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
