// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostGetSecurityEventHandlerFunc turns a function with the right signature into a post get security event handler
type PostGetSecurityEventHandlerFunc func(PostGetSecurityEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostGetSecurityEventHandlerFunc) Handle(params PostGetSecurityEventParams) middleware.Responder {
	return fn(params)
}

// PostGetSecurityEventHandler interface for that can handle valid post get security event params
type PostGetSecurityEventHandler interface {
	Handle(PostGetSecurityEventParams) middleware.Responder
}

// NewPostGetSecurityEvent creates a new http.Handler for the post get security event operation
func NewPostGetSecurityEvent(ctx *middleware.Context, handler PostGetSecurityEventHandler) *PostGetSecurityEvent {
	return &PostGetSecurityEvent{Context: ctx, Handler: handler}
}

/*
	PostGetSecurityEvent swagger:route POST /get/securityEvent postGetSecurityEvent

查询安全日志事件
*/
type PostGetSecurityEvent struct {
	Context *middleware.Context
	Handler PostGetSecurityEventHandler
}

func (o *PostGetSecurityEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostGetSecurityEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
