// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUpdataApplicationEventHandlerFunc turns a function with the right signature into a post updata application event handler
type PostUpdataApplicationEventHandlerFunc func(PostUpdataApplicationEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUpdataApplicationEventHandlerFunc) Handle(params PostUpdataApplicationEventParams) middleware.Responder {
	return fn(params)
}

// PostUpdataApplicationEventHandler interface for that can handle valid post updata application event params
type PostUpdataApplicationEventHandler interface {
	Handle(PostUpdataApplicationEventParams) middleware.Responder
}

// NewPostUpdataApplicationEvent creates a new http.Handler for the post updata application event operation
func NewPostUpdataApplicationEvent(ctx *middleware.Context, handler PostUpdataApplicationEventHandler) *PostUpdataApplicationEvent {
	return &PostUpdataApplicationEvent{Context: ctx, Handler: handler}
}

/*
	PostUpdataApplicationEvent swagger:route POST /updata/applicationEvent postUpdataApplicationEvent

上传应用日志事件
*/
type PostUpdataApplicationEvent struct {
	Context *middleware.Context
	Handler PostUpdataApplicationEventHandler
}

func (o *PostUpdataApplicationEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUpdataApplicationEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
