// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostGetClientIDHandlerFunc turns a function with the right signature into a post get client ID handler
type PostGetClientIDHandlerFunc func(PostGetClientIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostGetClientIDHandlerFunc) Handle(params PostGetClientIDParams) middleware.Responder {
	return fn(params)
}

// PostGetClientIDHandler interface for that can handle valid post get client ID params
type PostGetClientIDHandler interface {
	Handle(PostGetClientIDParams) middleware.Responder
}

// NewPostGetClientID creates a new http.Handler for the post get client ID operation
func NewPostGetClientID(ctx *middleware.Context, handler PostGetClientIDHandler) *PostGetClientID {
	return &PostGetClientID{Context: ctx, Handler: handler}
}

/*
	PostGetClientID swagger:route POST /getClientId postGetClientId

PostGetClientID post get client ID API
*/
type PostGetClientID struct {
	Context *middleware.Context
	Handler PostGetClientIDHandler
}

func (o *PostGetClientID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostGetClientIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
