// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostGetServiceEventHandlerFunc turns a function with the right signature into a post get service event handler
type PostGetServiceEventHandlerFunc func(PostGetServiceEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostGetServiceEventHandlerFunc) Handle(params PostGetServiceEventParams) middleware.Responder {
	return fn(params)
}

// PostGetServiceEventHandler interface for that can handle valid post get service event params
type PostGetServiceEventHandler interface {
	Handle(PostGetServiceEventParams) middleware.Responder
}

// NewPostGetServiceEvent creates a new http.Handler for the post get service event operation
func NewPostGetServiceEvent(ctx *middleware.Context, handler PostGetServiceEventHandler) *PostGetServiceEvent {
	return &PostGetServiceEvent{Context: ctx, Handler: handler}
}

/*
	PostGetServiceEvent swagger:route POST /get/serviceEvent postGetServiceEvent

查询服务事件
*/
type PostGetServiceEvent struct {
	Context *middleware.Context
	Handler PostGetServiceEventHandler
}

func (o *PostGetServiceEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostGetServiceEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
