// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"augeu/public/pkg/swaggerCore/models"
)

// PostRegisterOKCode is the HTTP code returned for type PostRegisterOK
const PostRegisterOKCode int = 200

/*
PostRegisterOK 注册成功

swagger:response postRegisterOK
*/
type PostRegisterOK struct {

	/*
	  In: Body
	*/
	Payload *models.RegisterResponse `json:"body,omitempty"`
}

// NewPostRegisterOK creates PostRegisterOK with default headers values
func NewPostRegisterOK() *PostRegisterOK {

	return &PostRegisterOK{}
}

// WithPayload adds the payload to the post register o k response
func (o *PostRegisterOK) WithPayload(payload *models.RegisterResponse) *PostRegisterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post register o k response
func (o *PostRegisterOK) SetPayload(payload *models.RegisterResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegisterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRegisterBadRequestCode is the HTTP code returned for type PostRegisterBadRequest
const PostRegisterBadRequestCode int = 400

/*
PostRegisterBadRequest 输入参数错误

swagger:response postRegisterBadRequest
*/
type PostRegisterBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequestError `json:"body,omitempty"`
}

// NewPostRegisterBadRequest creates PostRegisterBadRequest with default headers values
func NewPostRegisterBadRequest() *PostRegisterBadRequest {

	return &PostRegisterBadRequest{}
}

// WithPayload adds the payload to the post register bad request response
func (o *PostRegisterBadRequest) WithPayload(payload *models.BadRequestError) *PostRegisterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post register bad request response
func (o *PostRegisterBadRequest) SetPayload(payload *models.BadRequestError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegisterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostRegisterInternalServerErrorCode is the HTTP code returned for type PostRegisterInternalServerError
const PostRegisterInternalServerErrorCode int = 500

/*
PostRegisterInternalServerError 内部错误

swagger:response postRegisterInternalServerError
*/
type PostRegisterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ActionFailure `json:"body,omitempty"`
}

// NewPostRegisterInternalServerError creates PostRegisterInternalServerError with default headers values
func NewPostRegisterInternalServerError() *PostRegisterInternalServerError {

	return &PostRegisterInternalServerError{}
}

// WithPayload adds the payload to the post register internal server error response
func (o *PostRegisterInternalServerError) WithPayload(payload *models.ActionFailure) *PostRegisterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post register internal server error response
func (o *PostRegisterInternalServerError) SetPayload(payload *models.ActionFailure) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegisterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
