// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostUploadUserInfoHandlerFunc turns a function with the right signature into a post upload user info handler
type PostUploadUserInfoHandlerFunc func(PostUploadUserInfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUploadUserInfoHandlerFunc) Handle(params PostUploadUserInfoParams) middleware.Responder {
	return fn(params)
}

// PostUploadUserInfoHandler interface for that can handle valid post upload user info params
type PostUploadUserInfoHandler interface {
	Handle(PostUploadUserInfoParams) middleware.Responder
}

// NewPostUploadUserInfo creates a new http.Handler for the post upload user info operation
func NewPostUploadUserInfo(ctx *middleware.Context, handler PostUploadUserInfoHandler) *PostUploadUserInfo {
	return &PostUploadUserInfo{Context: ctx, Handler: handler}
}

/*
	PostUploadUserInfo swagger:route POST /upload/userInfo postUploadUserInfo

上传用户信息
*/
type PostUploadUserInfo struct {
	Context *middleware.Context
	Handler PostUploadUserInfoHandler
}

func (o *PostUploadUserInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUploadUserInfoParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
