// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostGetRdpEventHandlerFunc turns a function with the right signature into a post get rdp event handler
type PostGetRdpEventHandlerFunc func(PostGetRdpEventParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostGetRdpEventHandlerFunc) Handle(params PostGetRdpEventParams) middleware.Responder {
	return fn(params)
}

// PostGetRdpEventHandler interface for that can handle valid post get rdp event params
type PostGetRdpEventHandler interface {
	Handle(PostGetRdpEventParams) middleware.Responder
}

// NewPostGetRdpEvent creates a new http.Handler for the post get rdp event operation
func NewPostGetRdpEvent(ctx *middleware.Context, handler PostGetRdpEventHandler) *PostGetRdpEvent {
	return &PostGetRdpEvent{Context: ctx, Handler: handler}
}

/*
	PostGetRdpEvent swagger:route POST /get/rdpEvent postGetRdpEvent

查询RDP事件
*/
type PostGetRdpEvent struct {
	Context *middleware.Context
	Handler PostGetRdpEventHandler
}

func (o *PostGetRdpEvent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostGetRdpEventParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
