// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CommonQuery common query
//
// swagger:model CommonQuery
type CommonQuery struct {

	// Uuid
	UUID string `json:"Uuid,omitempty"`

	// client Id
	ClientID string `json:"clientId,omitempty"`

	// ip
	IP string `json:"ip,omitempty"`
}

// Validate validates this common query
func (m *CommonQuery) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this common query based on context it is used
func (m *CommonQuery) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CommonQuery) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CommonQuery) UnmarshalBinary(b []byte) error {
	var res CommonQuery
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
