// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EventCreateProcess event create process
//
// swagger:model EventCreateProcess
type EventCreateProcess struct {

	// command line
	CommandLine string `json:"CommandLine,omitempty"`

	// create user
	CreateUser string `json:"Create_User,omitempty"`

	// create user domain
	CreateUserDomain string `json:"Create_User_Domain,omitempty"`

	// description
	Description string `json:"Description,omitempty"`

	// event ID
	EventID string `json:"EventID,omitempty"`

	// ID
	ID int64 `json:"ID,omitempty"`

	// new process name
	NewProcessName string `json:"NewProcessName,omitempty"`

	// parent process name
	ParentProcessName string `json:"ParentProcessName,omitempty"`

	// UUID
	UUID string `json:"UUID,omitempty"`
}

// Validate validates this event create process
func (m *EventCreateProcess) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this event create process based on context it is used
func (m *EventCreateProcess) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventCreateProcess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventCreateProcess) UnmarshalBinary(b []byte) error {
	var res EventCreateProcess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
