// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EventPowerShell event power shell
//
// swagger:model EventPowerShell
type EventPowerShell struct {

	// command
	Command string `json:"Command,omitempty"`

	// description
	Description string `json:"Description,omitempty"`

	// event ID
	EventID string `json:"EventID,omitempty"`

	// ID
	ID int64 `json:"ID,omitempty"`

	// UUID
	UUID string `json:"UUID,omitempty"`
}

// Validate validates this event power shell
func (m *EventPowerShell) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this event power shell based on context it is used
func (m *EventPowerShell) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventPowerShell) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventPowerShell) UnmarshalBinary(b []byte) error {
	var res EventPowerShell
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
