// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetLoginEventRequest get login event request
//
// swagger:model GetLoginEventRequest
type GetLoginEventRequest struct {

	// Uuid
	UUID string `json:"Uuid,omitempty"`

	// client Id
	ClientID string `json:"clientId,omitempty"`

	// ip
	IP string `json:"ip,omitempty"`

	// page and size
	// Required: true
	PageAndSize *PageAndSize `json:"pageAndSize"`
}

// Validate validates this get login event request
func (m *GetLoginEventRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePageAndSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetLoginEventRequest) validatePageAndSize(formats strfmt.Registry) error {

	if err := validate.Required("pageAndSize", "body", m.PageAndSize); err != nil {
		return err
	}

	if m.PageAndSize != nil {
		if err := m.PageAndSize.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pageAndSize")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pageAndSize")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get login event request based on the context it is used
func (m *GetLoginEventRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePageAndSize(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetLoginEventRequest) contextValidatePageAndSize(ctx context.Context, formats strfmt.Registry) error {

	if m.PageAndSize != nil {

		if err := m.PageAndSize.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pageAndSize")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pageAndSize")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetLoginEventRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetLoginEventRequest) UnmarshalBinary(b []byte) error {
	var res GetLoginEventRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
