// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PageMeta page meta
//
// swagger:model PageMeta
type PageMeta struct {

	// page
	Page *int64 `json:"page,omitempty"`

	// size
	Size *int64 `json:"size,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this page meta
func (m *PageMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this page meta based on context it is used
func (m *PageMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PageMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PageMeta) UnmarshalBinary(b []byte) error {
	var res PageMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
