// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceInfo service info
//
// swagger:model ServiceInfo
type ServiceInfo struct {

	// account
	Account string `json:"Account,omitempty"`

	// description
	Description string `json:"Description,omitempty"`

	// event ID
	EventID string `json:"EventID,omitempty"`

	// ID
	ID int64 `json:"ID,omitempty"`

	// image path
	ImagePath string `json:"ImagePath,omitempty"`

	// service name
	ServiceName string `json:"ServiceName,omitempty"`

	// start type
	StartType string `json:"StartType,omitempty"`

	// UUID
	UUID string `json:"UUID,omitempty"`
}

// Validate validates this service info
func (m *ServiceInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service info based on context it is used
func (m *ServiceInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceInfo) UnmarshalBinary(b []byte) error {
	var res ServiceInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
