// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SystemEvent system event
//
// swagger:model SystemEvent
type SystemEvent struct {

	// description
	Description string `json:"Description,omitempty"`

	// event ID
	EventID string `json:"EventID,omitempty"`

	// ID
	ID int64 `json:"ID,omitempty"`

	// level display name
	LevelDisplayName string `json:"LevelDisplayName,omitempty"`

	// UUID
	UUID string `json:"UUID,omitempty"`
}

// Validate validates this system event
func (m *SystemEvent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this system event based on context it is used
func (m *SystemEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SystemEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SystemEvent) UnmarshalBinary(b []byte) error {
	var res SystemEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
