// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserInfo user info
//
// swagger:model UserInfo
type UserInfo struct {

	// 描述
	// Required: true
	Description *string `json:"description"`

	// 是否是可疑的用户
	// Required: true
	IsFocus *bool `json:"isFocus"`

	// 是否本地账户
	// Required: true
	LocalAccount *bool `json:"localAccount"`

	// 名字
	// Required: true
	Name *string `json:"name"`

	// SID
	// Required: true
	Sid *string `json:"sid"`

	// UUID
	// Required: true
	UUID *string `json:"uuid"`
}

// Validate validates this user info
func (m *UserInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIsFocus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocalAccount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSid(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserInfo) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *UserInfo) validateIsFocus(formats strfmt.Registry) error {

	if err := validate.Required("isFocus", "body", m.IsFocus); err != nil {
		return err
	}

	return nil
}

func (m *UserInfo) validateLocalAccount(formats strfmt.Registry) error {

	if err := validate.Required("localAccount", "body", m.LocalAccount); err != nil {
		return err
	}

	return nil
}

func (m *UserInfo) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *UserInfo) validateSid(formats strfmt.Registry) error {

	if err := validate.Required("sid", "body", m.Sid); err != nil {
		return err
	}

	return nil
}

func (m *UserInfo) validateUUID(formats strfmt.Registry) error {

	if err := validate.Required("uuid", "body", m.UUID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user info based on context it is used
func (m *UserInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserInfo) UnmarshalBinary(b []byte) error {
	var res UserInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
